FROM python:3.7
LABEL maintainer="TEST"

ENV PYTHONUNBUFFERED 1
ENV PATH="/scripts:${PATH}"

RUN pip install --upgrade pip

RUN apt-get update -y
RUN apt-get install -y build-essential
RUN apt-get install -y postgresql-client

ADD ./requirements.txt /requirements.txt
RUN pip install -r /requirements.txt

RUN mkdir /app
WORKDIR /app
COPY ./app /app
COPY ./scripts /scripts
RUN chmod +x /scripts/*

RUN mkdir -p /vol/web/media
RUN mkdir -p /vol/web/static
RUN useradd -m user
RUN chown -R user:user /vol/
RUN chown -R user:user /app/templates
RUN chmod -R 755 /vol/web
USER user

CMD ["entrypoint.sh"]