# Generated by Django 3.0.9 on 2020-08-12 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YouTube', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetrevenueview',
            name='cms',
            field=models.CharField(choices=[('Music', 'Music'), ('Other', 'Other')], max_length=5),
        ),
    ]
