# Generated by Django 3.0.9 on 2020-08-14 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YouTube', '0002_auto_20200812_0312'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='office',
            field=models.CharField(choices=[('KR', 'Korea'), ('JP', 'Japan'), ('ID', 'Indonesia'), ('PH', 'Philippines')], max_length=2, null=True),
        ),
    ]
