# Generated by Django 3.0.9 on 2020-08-27 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('YouTube', '0003_manager_office'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaidFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_month', models.CharField(max_length=7)),
                ('amount', models.FloatField(default=0)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YouTube.Channel')),
            ],
        ),
    ]
